 <!-- Js Plugins -->
 <script src="{{ asset('js/shop/jquery-3.3.1.min.js') }}"></script>
 <script src="{{ asset('js/shop/bootstrap.min.js') }}"></script>
 <script src="{{ asset('js/shop/jquery.nice-select.min.js') }}"></script>
 <script src="{{ asset('js/shop/jquery-ui.min.js') }}"></script>
 <script src="{{ asset('js/shop/jquery.slicknav.js') }}"></script>
 <script src="{{ asset('js/shop/mixitup.min.js') }}"></script>
 <script src="{{ asset('js/shop/owl.carousel.min.js') }}"></script>
 <script src="{{ asset('js/shop/main.js') }}"></script>